### ISSUE TITLE
Firefox?

### ISSUE THREAD

**Issue by rice7th** [rkk3/ad-accelerator#10]
Firefox support would be awesome. Thanks in advance.

**Comment by GmGniap** [comment]
First of all , I want to say thanks to @rkk3 who initiate this skip idea and since that day I saw post on HN , I installed extension on Vivaldi browser and it was working well. I just read there's another extension launched as a copy of this one and I'm so sorry to hear that they didn't give enough credit to your idea. 

+1 for Firefox browser support.

**Comment by sgreer2** [comment]
@rkk3 I think a separate branch for Firefox would probably be the best option. Then with every update of the main branch you could just rebase the Firefox branch.
