### ISSUE TITLE
Kiwi Browser on Android

### ISSUE THREAD

**Issue by bonelifer** [rkk3/ad-accelerator#3]
It mutes it and I cant unmute it after the ad, unless I refresh the page. Isn't it supposed to unmute after the ad? None of the controls work till I refresh.

**Comment by rkk3** [comment]
Thanks for letting me know.

Yes the expected behavior is to only mute & increase the speed of the ad. 

I built the extension for Chrome (on mac Os) & did not test at all for the Kiwi Browser on Android. I will see if I can reproduce & resolve the issue, but in the meantime it sounds like you may want to disable the extension.
